[library]
version = "1.0"
browse_url = "https://github.com/pojntfx/senbara"
repository_url = "https://github.com/pojntfx/senbara.git"
website_url = "https://github.com/pojntfx/senbara"
authors = "Felicitas Pojtinger"
license = "AGPL-3.0"
description = "Senbara PureGoTK - A GTK4 widget library built with Go and PureGoTK"
dependencies = ["GObject-2.0", "Gtk-4.0"]
devhelp = true
search_index = true

[theme]
name = "basic"
show_index_summary = true
show_class_hierarchy = true

[source-location]
base_url = "https://github.com/pojntfx/senbara/blob/main/senbara-gnome-puregotk/"

[extra]
content_files = []
content_images = []